version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sidedominicana
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: 251020/sidedominicana:1.1
    container_name: my_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:sidedominicana@postgres_db:5432/postgres
      SSL_CERT_PATH: /certs/fullchain.pem
      SSL_KEY_PATH: /certs/privkey.pem
    ports:
      - "443:3000"
    volumes:
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/certs/privkey.pem

volumes:
  postgres_data:
